name: ci
on:
  push:
    paths-ignore:
      - 'README.md'
    branches:
      - '**'

jobs:
  buildx:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Get Version
        id: get_version
        uses: battila7/get-version-action@v2.3.0

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v3

      - name: Available platforms
        run: echo ${{ steps.buildx.outputs.platforms }}

      - name: Build Docker images
        uses: docker/build-push-action@v6
        with:
          context: .
          platforms: |
            linux/amd64,
            linux/arm64,
            linux/arm/v7,
            linux/arm/v6,
            linux/386,
            linux/ppc64le,
            linux/s390x,
            linux/riscv64
          cache-from: type=gha
          cache-to: type=gha,mode=max